### ISSUE TITLE
Translate static content to different languages

### ISSUE THREAD

**Issue by dimpiax** [maxwelld90/medicine-for-ukraine#10]

**Comment by maxwelld90** [comment]
We need someone to create content for the index and about pages, and translate them to all available languages. This task will also include getting a list of contributor names, pictures and contact links (where applicable). Do we only list the people who made the website? Or do we also go further afield and list ALL people on the M4U project?

**Comment by dimpiax** [comment]
do we have the mock-ups for these pages?

**Comment by maxwelld90** [comment]
Completed.
