### ISSUE TITLE
Integrate LANGUAGE.json with React app (unify what languages are available)

### ISSUE THREAD

**Issue by dimpiax** [maxwelld90/medicine-for-ukraine#16]

**Comment by maxwelld90** [comment]
`LANGUAGES.json` is a new file containing a JSON object listing all available languages. This will be the point of contact for language information for both the static content, and the React app (when building).

**Comment by maxwelld90** [comment]
Completed. The React app, when compiling, uses the LANGUAGES.json file to work out what languages are available.
