### ISSUE TITLE
Medicine Reader capitalisation (or not) issue

### ISSUE THREAD

**Issue by maxwelld90** [maxwelld90/medicine-for-ukraine#24]
The medicine reader class (https://github.com/maxwelld90/medicine-for-ukraine/blob/main/api/api_app/items/medicine_reader.py) and associated code are using a mix of upper case and lower case for country code matching. This is causing issues!

Ideally, I think all column names and country codes should be normalised to lower case for comparison.

If someone wants to take this on, please do!

**Comment by dimpiax** [comment]
This seems to be related to the back-end, and the included file can't be find anymore.
@maxwelld90 is it the problem still actual?

**Comment by maxwelld90** [comment]
Yes it is now solved.
