### ISSUE TITLE
Fix UI bugs

### ISSUE THREAD

**Issue by nataljadj** [maxwelld90/medicine-for-ukraine#36]
Look at the attached image 

- [x] Step 2/5: Background price width
- [x] Step 3/5: Real price value and tooltip 
- [x] Thanks page Remove "Back" button

**Comment by nataljadj** [comment]
![Image from iOS](https://user-images.githubusercontent.com/9337083/162763981-6860837a-8a9f-45dc-93d4-e85f58c5b1a2.jpg)

**Comment by svakulenk0** [comment]
@maxwelld90 ?

**Comment by nataljadj** [comment]
https://github.com/maxwelld90/medicine-for-ukraine/commit/52e60796a6ae4113cc0849796613b75ca484c242
